[package]
description = "CosmWasm integration testing for Desmos"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "desmos-test-tube"
repository = "https://github.com/manu0466/desmos-test-tube"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
cosmrs = {version = "0.14.0", features = ["cosmwasm"]}
desmos-bindings = { version = "2.0.1" }
cosmwasm-std = "1.3.0"
prost = "0.11.9"
serde = "1.0.171"
serde_json = "1.0.103"
test-tube = {version = "0.1.6", path = "../test-tube"}
thiserror = "1.0.43"

[dev-dependencies]
hex = { version = "0.4.3" }

[build-dependencies]
bindgen = "0.66.1"